name: process_audio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipython
  - ipykernel
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - psutil
  - pygments
  - traitlets
  - tornado
  - zeromq
  - setuptools
  - wheel
  - six
  - packaging
  - numpy
  - scipy
  - scikit-learn
  - cython
  - pip:
      - audioread==3.0.1
      - librosa==0.9.2
      - madmom==0.16.1
      - mido==1.3.3
      - matplotlib==3.5.3
      - numba==0.55.2
      - soundfile==0.13.1
      - resampy==0.4.3
      - soxr==0.5.0.post1
      - joblib==1.5.2
      - threadpoolctl==3.6.0
      - requests==2.32.5
      - pyrubberband==0.4.0
