name: cnn-embeddings
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - umap-learn
  - hdbscan
  - pip:
      - timm
